import textwrap
from tempfile import TemporaryDirectory
from pathlib import Path

import pytest

from pipfreeze2nix import pip_compile_parser


@pytest.fixture
def tmp_path():
    with TemporaryDirectory() as tmp_dir:
        yield Path(tmp_dir)


def test_parse_compiled_requirements__simple(tmp_path):
    (tmp_path / "requirements.txt").write_text(textwrap.dedent(
        """\
        #
        # This file is autogenerated by pip-compile with Python 3.10
        # by the following command:
        #
        #    pip-compile
        #
        --index-url https://artifactory.lyft.net/artifactory/api/pypi/virtual-pypi-lyft/simple/

        certifi==2022.12.7
            # via requests
        charset-normalizer==2.1.1
            # via requests
        idna==3.4
            # via requests
        packaging==22.0
            # via -r requirements.in
        requests==2.28.1
            # via -r requirements.in
        urllib3==1.26.13
            # via requests
        """
    ))

    requirement_trees = pip_compile_parser.parse_compiled_requirements(tmp_path / "requirements.txt")
    assert requirement_trees == {
        "certifi": pip_compile_parser.RequirementTree("certifi"),
        "charset-normalizer": pip_compile_parser.RequirementTree("charset-normalizer"),
        "idna": pip_compile_parser.RequirementTree("idna"),
        "packaging": pip_compile_parser.RequirementTree("packaging"),
        "requests": pip_compile_parser.RequirementTree(
            "requests",
            dependencies={
                "certifi",
                "charset-normalizer",
                "idna",
                "urllib3",
            },
        ),
        "urllib3": pip_compile_parser.RequirementTree("urllib3"),
    }
